services:
  web-downloader-track:
    image: alpine
    command: /home/docker/web-downloader/web-downloader.sh
    environment:
      - TEAMCITY_TAG=${TRACK_WEB_VERSION:?required}
      - TEAMCITY_BUILD_NAME=MaintainVbenAdmin_Release
      - TEAMCITY_BUILD_ZIP_NAME=maintain.zip
      - NGINX_HTML_DIR_NAME=track
    volumes:
      - "${DATA_DIR:-/data}/nginx/html:/data/nginx/html"
    configs:
      - source: web-downloader.sh
        target: /home/docker/web-downloader/web-downloader.sh
      - source: teamcity-download-artifact.sh
        target: /home/docker/projects/teamcity-download-artifact.sh

configs:
  web-downloader.sh:
    file: ./web-downloader.sh
  teamcity-download-artifact.sh:
    file: ../projects/teamcity-download-artifact.sh
