services:
  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
      - "5000:5000"
    secrets:
      - ssl-certificate-crt
      - ssl-certificate-key
    volumes:
      - /data/docker/registry:/var/lib/registry
      - /home/docker-compose/auth:/auth
      #- /home/docker-compose/docker-registry/ssl:/ssl
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_HTTP_TLS_CERTIFICATE: /run/secrets/ssl-certificate-crt
      REGISTRY_HTTP_TLS_KEY: /run/secrets/ssl-certificate-key
  registry-ui:
    image: joxit/docker-registry-ui:main
    container_name: registry-ui
    restart: always
    ports:
      - 5080:80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=https://transcodegroup.cn:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
    depends_on:
      - registry
secrets:
  ssl-certificate-crt:
    file: ${SSL_CERTIFICATE:?required}.crt
  ssl-certificate-key:
    file: ${SSL_CERTIFICATE:?required}.key