services:
  nginx:
    image: nginx:1.22.1
    container_name: nginx
    restart: always
    ports:
      - 443:443
      # 视频直播,映射srs端口
      - ${VIDEO_PORT_HTTPS_1}:${VIDEO_PORT_HTTPS_1}
      - ${VIDEO_PORT_HTTPS_2}:${VIDEO_PORT_HTTPS_2}
      - ${VIDEO_PORT_HTTPS_3}:${VIDEO_PORT_HTTPS_3}
      - ${VIDEO_PORT_HTTPS_4}:${VIDEO_PORT_HTTPS_4}
      - ${VIDEO_PORT_HTTPS_5}:${VIDEO_PORT_HTTPS_5}
    privileged: true
    depends_on:
      - srs
      - rtp
    volumes:
      - "/home/docker/docker-nginx/ssl:/etc/nginx/ssl"
      - "/home/docker/docker-nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      # 使用配置文件模板, 后缀需要是.conf.tempalte
      # https://hub.docker.com/_/nginx#:~:text=Using%20environment%20variables
      - "/home/docker/docker-nginx/conf/conf.d:/etc/nginx/templates"
      - "/home/docker/docker-nginx/html:/usr/share/nginx/html"
      - "/data/nginx/logs:/var/log/nginx"
    environment:
      - VIDEO_PORT_HTTPS_1=${VIDEO_PORT_HTTPS_1}
      - VIDEO_PORT_HTTPS_2=${VIDEO_PORT_HTTPS_2}
      - VIDEO_PORT_HTTPS_3=${VIDEO_PORT_HTTPS_3}
      - VIDEO_PORT_HTTPS_4=${VIDEO_PORT_HTTPS_4}
      - VIDEO_PORT_HTTPS_5=${VIDEO_PORT_HTTPS_5}
      - VIDEO_SSL_CERTIFICATE=${VIDEO_SSL_CERTIFICATE}

