services:
  nginx:
    image: nginx:1.22.1
    container_name: nginx
    restart: always
    ports:
      - 443:443
      # 视频直播,映射srs端口
      - 9085-9089:9085-9089
    privileged: true
    depends_on:
      - srs
      - rtp
    volumes:
      - "/home/docker/docker-nginx/ssl:/etc/nginx/ssl"
      - "/home/docker/docker-nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "/home/docker/docker-nginx/conf/conf.d:/etc/nginx/conf.d"
      - "/home/docker/docker-nginx/html:/usr/share/nginx/html"
      - "/data/nginx/logs:/var/log/nginx"