services:
  srs:
    image: ossrs/srs:v6.0-a1
    container_name: srs
    restart: always
    ports:
      # rtmp端口(rtp和app使用)
      - 9005:1935
      # api端口,建议nginx代理, 内部别名访问
      #- 1985:1985
      # http-flv/hls端口,建议nginx代理, 内部别名访问
      #- 8080:8080
    volumes:
      - "/home/docker/docker-rtp/srs/conf:/usr/local/srs/conf"
      - "/data/srs/html:/usr/local/srs/objs/nginx/html"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    logging: 
      driver: "json-file"
      options:
        # 限制日志文件大小
        max-size: "100m"
  # rtp推流服务
  rtp:
    image: transcodegroup/gateway-rtpserver:23.8.3
    container_name: rtp
    restart: always
    ports:
      # 终端-实时直播端口
      - 9000:9000
      # 终端-录像回放端口
      - 9001:9001
      # 终端-对讲
      - 9002:9002
      # 终端-终端监听
      - 9003:9003
      # 客户端-对讲和api服务接口,建议nginx代理, 内部别名访问
      - 9006:9006     
    volumes:
      - "/data/logs/rtp:/logs"
    environment:
      # 服务节点名称
      - gateway_zone=live-58_82_168_181
      # 外网地址, 注册到网关
      - gateway_host=58.82.168.181
      # 客户端通过 ws://localhost:8080/ws/talk对讲, monitor监听, nginx代理端口
      - gateway_wss=wss://livedvr.tripsdd.com/ws
      # 网关服务注册地址, 建议使用域名
      - gateway_media_enabled=true
      - gateway_media_api=http://103.20.204.149:9012
      # 终端连接端口, 建议使用默认值
      - gateway_port_live=9000
      - gateway_port_record=9001
      - gateway_port_talk=9002
      - gateway_port_monitor=9003
      # rtp连接srs, 建议使用默认值
      - gateway_srs_rtmp=rtmp://srs:1935
      - gateway_srs_api=http://srs:1985
      # 是否启用redis支持 默认禁用, Bus平台建议开启， V2建议关闭
      - spring_data_redis_repositories_enabled=false
      # APP的RTMP连接
      - gateway_srs_wan_rtmp=rtmp://58.82.168.181:9005
      # 前端http-flv地址, 支持多个用逗号分隔
      - gateway_srs_wan_http=https://livedvr.tripsdd.com:9085/mdvr,https://livedvr.tripsdd.com:9086/mdvr,https://livedvr.tripsdd.com:9087/mdvr,https://livedvr.tripsdd.com:9088/mdvr,https://livedvr.tripsdd.com:9089/mdvr
    depends_on:
      - srs
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    logging: 
      driver: "json-file"
      options:
        # 限制日志文件大小
        max-size: "100m"
