services:
  mysql8:
    image: mysql:8.4
    # 国内拦了 用加速站
    #image: docker.m.daocloud.io/mysql:8.4
    container_name: mysql8
    restart: always
    ports:
      - ${MYSQL_PORT:-3306}:3306
    configs:
      - source: mysql8.conf
        target: /etc/mysql/conf.d
      - source: mysql8.initdb
        target: /docker-entrypoint-initdb.d
    volumes:
      - "/data/mysql8/data:/var/lib/mysql"
      - "/data/mysql8/logs:/var/log/mysql"
      - "/data/mysql8/backup/database:/mysql/backup/database"
      - "/data/mysql8/backup/log:/mysql/backup/log"
    environment:
      # 设置密码
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:?required}
    logging: 
      driver: "json-file"
      options:
        # 限制日志文件大小
        max-size: "100m"
configs:
  mysql8.conf:
    file: ./conf
  mysql8.initdb:
    file: ./initdb