services:
  srs:
    volumes:
      - "/home/docker/video/srs-storage/conf:/usr/local/srs/conf"
      - "/data/srs-storage/html:/usr/local/srs/objs/nginx/html"
  rtp:
    volumes:
      - "/data/logs/rtp-storage:/logs"
      - "/data/srs-storage/html/dvr/live:/data/record"
    depends_on:
      - minio
    environment:
      # 启用存储 true=推流不判断超时
      - gateway_dvr_enabled=true
      # 启用mini 录像将存放minio中do
      - spring_minio_enabled=true
      - spring_minio_domain=https://${VIDEO_HOSTNAME:?required}:${VIDEO_PORT_HTTPS_0}/minio
      - spring_minio_endpoint=http://${MINIO_HOST:-minio}:${MINIO_PORT:-8000}
      - spring_minio_accessKey=${MINIO_ACCESSKEY:?required}
      - spring_minio_secretKey=${MINIO_SECRETKEY:?required}
      - spring_minio_bucketName=storage
      # 启用mq通道 存储成功后通知mp并删除文件
      - spring_rabbitmq_enabled=true
      - spring_rabbitmq_host=${RABBITMQ_HOST:-rabbitmq}
      - spring_rabbitmq_port=${RABBITMQ_PORT:-5672}
      - spring_rabbitmq_username=${RABBITMQ_USERNAME:-admin}
      - spring_rabbitmq_password=${RABBITMQ_PASSWORD:?required}
      - spring_rabbitmq_virtual-host=/track
