services:
  srs:
    image: ossrs/srs:v6.0-a1
    container_name: srs
    restart: always
    ports:
      # rtmp端口(rtp和app使用)
      - ${VIDEO_PORT_RTMP}:1935
      # api端口,建议nginx代理, 内部别名访问
      #- 1985:1985
      # http-flv/hls端口,建议nginx代理, 内部别名访问
      #- 8080:8080
    volumes:
      - "/home/docker/video/srs/conf:/usr/local/srs/conf"
      - "/data/srs/html:/usr/local/srs/objs/nginx/html"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    logging: 
      driver: "json-file"
      options:
        # 限制日志文件大小
        max-size: "100m"
  # rtp推流服务
  rtp:
    image: transcodegroup/gateway-rtpserver:23.8.3
    container_name: rtp
    restart: always
    ports:
      # 终端-实时直播端口
      - ${VIDEO_PORT_LIVE}:${VIDEO_PORT_LIVE}
      # 终端-录像回放端口
      - ${VIDEO_PORT_RECORD}:${VIDEO_PORT_RECORD}
      # 终端-对讲
      - ${VIDEO_PORT_TALK}:${VIDEO_PORT_TALK}
      # 终端-终端监听
      - ${VIDEO_PORT_MONITOR}:${VIDEO_PORT_MONITOR}
      # 客户端-对讲和api服务接口,建议nginx代理, 内部别名访问
      # - 9006:9006
    volumes:
      - "/data/logs/rtp:/logs"
    environment:
      # 服务节点名称
      - gateway_zone=live-${VIDEO_IP:?required}
      # 外网地址, 注册到网关
      - gateway_host=${VIDEO_IP:?required}
      # 客户端通过 ws://localhost:8080/ws/talk对讲, monitor监听, nginx代理端口
      - gateway_wss=wss://${VIDEO_HOSTNAME:?required}/ws
      # 网关服务注册地址, 建议使用域名
      - gateway_media_enabled=true
      - gateway_media_api=http://${GATEWAY_HOSTNAME:?required}:${GATEWAY_PORT}
      # 终端连接端口, 建议使用默认值
      - gateway_port_live=${VIDEO_PORT_LIVE}
      - gateway_port_record=${VIDEO_PORT_RECORD}
      - gateway_port_talk=${VIDEO_PORT_TALK}
      - gateway_port_monitor=${VIDEO_PORT_MONITOR}
      # rtp连接srs, 建议使用默认值
      - gateway_srs_rtmp=rtmp://srs:1935
      - gateway_srs_api=http://srs:1985
      # 是否启用redis支持 默认禁用, Bus平台建议开启， V2建议关闭
      - spring_data_redis_repositories_enabled=false
      # APP的RTMP连接
      - gateway_srs_wan_rtmp=rtmp://${VIDEO_IP:?required}:${VIDEO_PORT_RTMP}
      # 前端http-flv地址, 支持多个用逗号分隔
      - gateway_srs_wan_http=https://${VIDEO_HOSTNAME:?required}:${VIDEO_PORT_HTTPS_1}/mdvr,https://${VIDEO_HOSTNAME:?required}:${VIDEO_PORT_HTTPS_2}/mdvr,https://${VIDEO_HOSTNAME:?required}:${VIDEO_PORT_HTTPS_3}/mdvr,https://${VIDEO_HOSTNAME:?required}:${VIDEO_PORT_HTTPS_4}/mdvr,https://${VIDEO_HOSTNAME:?required}:${VIDEO_PORT_HTTPS_5}/mdvr
    depends_on:
      - srs
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    logging: 
      driver: "json-file"
      options:
        # 限制日志文件大小
        max-size: "100m"
