services:
  srs:
    volumes:
      - "/home/docker/video/srs-storage/conf:/usr/local/srs/conf"
      - "/data/srs-storage/html:/usr/local/srs/objs/nginx/html"
  rtp:
    volumes:
      - "/data/logs/rtp-storage:/logs"
      - "/data/srs-storage/html/dvr/live:/data/record"
    environment:
      # 启用存储 true=推流不判断超时
      - gateway_dvr_enabled=true
      # 启用mini 录像将存放minio中do
      - spring_minio_enabled=true
      - spring_minio_domain=https://${VIDEO_HOSTNAME:?required}/minio
      - spring_minio_endpoint=http://minio:9000
      - spring_minio_accessKey=${MINIO_ACCESSKEY:?required}
      - spring_minio_secretKey=${MINIO_SECRETKEY:?required}
      - spring_minio_bucketName=storage
      # 启用mq通道 存储成功后通知mp并删除文件
      - spring_rabbitmq_enabled=true
      - spring_rabbitmq_host=${SRPING_RABBITMQ_HOST:?required}
      - spring_rabbitmq_port=${SRPING_RABBITMQ_PORT}
      - spring_rabbitmq_username=${SRPING_RABBITMQ_USERNAME:?required}
      - spring_rabbitmq_password=${SRPING_RABBITMQ_PASSWORD:?required}
      - spring_rabbitmq_virtual-host=/track
