services:
  nginx:
    ports:
      # 视频直播,映射srs端口
      - ${VIDEO_PORT_HTTPS_0}:${VIDEO_PORT_HTTPS_0}
      - ${VIDEO_PORT_HTTPS_1}:${VIDEO_PORT_HTTPS_1}
      - ${VIDEO_PORT_HTTPS_2}:${VIDEO_PORT_HTTPS_2}
      - ${VIDEO_PORT_HTTPS_3}:${VIDEO_PORT_HTTPS_3}
      - ${VIDEO_PORT_HTTPS_4}:${VIDEO_PORT_HTTPS_4}
      - ${VIDEO_PORT_HTTPS_5}:${VIDEO_PORT_HTTPS_5}
    depends_on:
      - srs
      - rtp
    secrets:
      - video-ssl-certificate
      - video-ssl-certificate-key
    configs:
      # 默认启动https的配置
      - source: video-https.conf.template
        target: /etc/nginx/templates/video.conf.template
    environment:
      - VIDEO_PORT_HTTPS_0=${VIDEO_PORT_HTTPS_0}
      - VIDEO_PORT_HTTPS_1=${VIDEO_PORT_HTTPS_1}
      - VIDEO_PORT_HTTPS_2=${VIDEO_PORT_HTTPS_2}
      - VIDEO_PORT_HTTPS_3=${VIDEO_PORT_HTTPS_3}
      - VIDEO_PORT_HTTPS_4=${VIDEO_PORT_HTTPS_4}
      - VIDEO_PORT_HTTPS_5=${VIDEO_PORT_HTTPS_5}

secrets:
  video-ssl-certificate:
    file: ${VIDEO_SSL_CERTIFICATE:?required}.crt
  video-ssl-certificate-key:
    file: ${VIDEO_SSL_CERTIFICATE:?required}.key

configs:
  video-https.conf.template:
    file: ./conf/conf.d/video-https.conf.template
