services:
  nginx:
    image: nginx:1.27.4
    container_name: nginx
    restart: always
    ports:
      # 默认443和80
      - ${WEB_PORT_HTTPS}:443
      - ${WEB_PORT_HTTP}:80
    privileged: true
    secrets:
      - ssl-certificate
      - ssl-certificate-key
    volumes:
      - "/data/nginx/html:/usr/share/nginx/html"
      - "/data/nginx/logs:/var/log/nginx"
    configs:
      - source: nginx.conf
        target: /etc/nginx/nginx.conf
    environment:
      - JTT808_PORT_HTTP=${JTT808_PORT_HTTP}

secrets:
  ssl-certificate:
    file: ${SSL_CERTIFICATE:?required}.crt
  ssl-certificate-key:
    file: ${SSL_CERTIFICATE:?required}.key

configs:
  nginx.conf:
    file: ./conf/nginx.conf
  bus.conf.template:
    file: ./conf/conf.d/bus.conf.template
  track.conf.template:
    file: ./conf/conf.d/track.conf.template