services:
  video-nginx:
    configs:
      # 使用http的配置覆盖
      - source: mdvr-live-http.conf.template
        target: /etc/nginx/templates/mdvr-live.conf.template

configs:
  mdvr-live-http.conf.template:
    file: ./conf/conf.d/mdvr-live-http.conf.template
