services:
  minio:
    image: minio/minio:RELEASE.2024-08-03T04-33-23Z
    container_name: minio
    restart: always
    ports:
       # 原生端口是9000和9001, 规避RTP服务端口冲突, 所以-1000
      - ${MINIO_PORT:-8000}:${MINIO_PORT:-8000}
      - ${MINIO_PORT_HTTP:-8001}:${MINIO_PORT_HTTP:-8001}
    environment:
      - MINIO_ROOT_USER=${MINIO_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD:?required}
      - MINIO_BROWSER_REDIRECT_URL=${WEB_BASE_URL:?required}
    volumes:
      - "/data/minio-data:/data"
    command: server /data --console-address ":${MINIO_PORT_HTTP:-8001}" --address ":${MINIO_PORT:-8000}"
    logging: 
      driver: "json-file"
      options:
         max-size: "100m"