services:
  redis:
    image: redis
    container_name: redis
    restart: always
    # 启用持久化 增加密码 降低日志级别 限制数据库数量 
    command: --appendonly yes --requirepass "${REDIS_PASSWORD:?required}" --loglevel warning --databases 3
    volumes:
      - ${DATA_DIR:-/data}/redis/data:/data
    ports:
      - ${REDIS_PORT:-6379}:6379
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
